# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Increase command timeout, git is slow in discord repo
command_timeout = 1000

[container]
format = "[$symbol]($style) "

# This doesn't add much to my workflow
[package]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[buf]
disabled = true

[python]
python_binary = ['python3', 'python', 'python2']
