prompt_prefix = ""
forward_env = ["SSH_CONNECTION", "CODER_WORKSPACE_NAME", "CODER_WORKSPACE_AGENT_NAME", "CODER_AGENT_TOKEN", "CODER_AGENT_AUTH", "CODER_WORKSPACE_OWNER_NAME", "CODER", "CODER_WORKSPACE_ID", "CODER_AGENT_URL", "CODER_USER_EMAIL", "LANG"]

[[keybinding]]
binding = "Ctrl-a d"
action = "detach"
